buffer( 1)=nx
buffer( 2)=ncol_o
buffer( 3)=iannee
buffer( 4)=imois
buffer( 5)=ijour
buffer( 6)=iheure
buffer( 7)=iminute
buffer( 8)=seconde
buffer( 9)=intpas
buffer(10)=longeo
buffer(11)=latgeo
buffer(12)=lonmag
buffer(13)=latmag
buffer(14)=tmag
buffer(15)=f107(2)
buffer(16)=f107(3)
buffer(17)=ap(2)
buffer(18)=kptime
buffer(19)=dTinf
buffer(20)=dUinf
buffer(21)=cofo
buffer(22)=cofh
buffer(23)=cofn
buffer(24)=chi0
buffer(25)=Fe0
buffer(26)=Ee0
buffer(27)=Fi0
buffer(28)=Ei0
buffer(29)=Bmag
buffer(30)=dipangle
buffer(31)=Enord
buffer(32)=Eest
buffer(33)=vperpnord
buffer(34)=vperpest
buffer(35)=vhorizon
buffer(36)=vpara
buffer(37)=iapprox_o
buffer(38)=ddp
buffer(39)=Jtop
buffer(60)=1
do i=1,nb_alt
  ipos=(i+1)*ncol
  buffer(ipos+ipos_o%z)     =alt(i)
  buffer(ipos+ipos_o%n1)    =N_o*N1new(i)
  buffer(ipos+ipos_o%n2)    =N_o*N2new(i)
  buffer(ipos+ipos_o%n3)    =N_o*N3new(i)
  buffer(ipos+ipos_o%n4)    =N_o*N4new(i)
  buffer(ipos+ipos_o%n5)    =N_o*N5new(i)
  buffer(ipos+ipos_o%n6)    =N_o*N6new(i)
  buffer(ipos+ipos_o%u1)    =C_o(1)*U1new(i)
  buffer(ipos+ipos_o%u2)    =C_o(2)*U2new(i)
  buffer(ipos+ipos_o%u3)    =C_o(3)*U3new(i)
  buffer(ipos+ipos_o%um)    =C_o(4)*Umnew(i)
  buffer(ipos+ipos_o%ue)    =C_o(nb_ion)*Uenew(i)
  buffer(ipos+ipos_o%t1p)   =T_o*T1pnew(i)
  buffer(ipos+ipos_o%t1t)   =T_o*T1tnew(i)
  buffer(ipos+ipos_o%t2p)   =T_o*T2pnew(i)
  buffer(ipos+ipos_o%t2t)   =T_o*T2tnew(i)
  buffer(ipos+ipos_o%t3p)   =T_o*T3pnew(i)
  buffer(ipos+ipos_o%t3t)   =T_o*T3tnew(i)
  buffer(ipos+ipos_o%tmp)   =T_o*Tmpnew(i)
  buffer(ipos+ipos_o%tmt)   =T_o*Tmtnew(i)
  buffer(ipos+ipos_o%tep)   =T_o*Tepnew(i)
  buffer(ipos+ipos_o%tet)   =T_o*Tetnew(i)
  buffer(ipos+ipos_o%q1)    =q_o(1)*q1new(i)
  buffer(ipos+ipos_o%q2)    =q_o(2)*q2new(i)
  buffer(ipos+ipos_o%q3)    =q_o(3)*q3new(i)
  buffer(ipos+ipos_o%qe)    =q_o(nb_ion)*qenew(i)
  buffer(ipos+ipos_o%nno)   =N_o*Nnonew(i)
  buffer(ipos+ipos_o%uno)   =Co(5)*Unonew(i)
  buffer(ipos+ipos_o%po)    =Po(i)*N_o/to
  buffer(ipos+ipos_o%ph)    =Ph(i)*N_o/to
  buffer(ipos+ipos_o%pn)    =Pn(i)*N_o/to
  buffer(ipos+ipos_o%pn2)   =Pn2(i)*N_o/to
  buffer(ipos+ipos_o%po2)   =Po2(i)*N_o/to
  buffer(ipos+ipos_o%heat)  =Heat(i)
  buffer(ipos+ipos_o%no)    =No(i)
  buffer(ipos+ipos_o%nh)    =Nh(i)
  buffer(ipos+ipos_o%nn)    =Nn(i)
  buffer(ipos+ipos_o%nn2)   =Nn2(i)
  buffer(ipos+ipos_o%no2)   =No2(i)
  buffer(ipos+ipos_o%tn)    =Tn(i)
  buffer(ipos+ipos_o%un)    =Un(i)
  buffer(ipos+ipos_o%vn)    =Vn(i)
  buffer(ipos+ipos_o%wn)    =Wn(i)
  buffer(ipos+ipos_o%nes)   =Nes(i)
  buffer(ipos+ipos_o%jes)   =Jes(i)
  buffer(ipos+ipos_o%tes)   =Tes(i)
  buffer(ipos+ipos_o%qes)   =Qes(i)
enddo
