name: ci_unix

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - "**.py"
      - ".github/workflows/ci_unix.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install prereqs
      run: pip install -e .[tests]

    - run: mypy

    - run: cmake -B build
    - run: cmake --build build

    - run: pytest
